steps:
  - label: ":bazel: Build"
    commands:
      - "echo '--- Prepare environment'"
      - sudo apt-get install wget tree libdatetime-perl libdatetime-format-dateparse-perl libcapture-tiny-perl -y
      - wget https://github.com/bazelbuild/bazelisk/releases/download/v1.20.0/bazelisk-linux-amd64
      - chmod +x bazelisk-linux-amd64
      - sudo mv bazelisk-linux-amd64 /usr/local/bin/bazel
      - .buildkite/build-bazel.sh

    artifact_paths: 
      - bazel-testlogs/tests/dg-query_test/test.xml

  - label: ":bazel: Build in Docker"
    commands:
      - "echo '--- Prepare environment'"
      - sudo apt-get install wget
      - wget https://github.com/bazelbuild/bazelisk/releases/download/v1.20.0/bazelisk-linux-amd64
      - chmod +x bazelisk-linux-amd64
      - sudo mv bazelisk-linux-amd64 /usr/local/bin/bazel
      - .buildkite/build-bazel-docker.sh

  - label: ":bazel: Build remote (BuildBuddy)"
    commands:
      - "echo '--- Prepare environment'"
      - sudo apt-get install wget
      - wget https://github.com/bazelbuild/bazelisk/releases/download/v1.20.0/bazelisk-linux-amd64
      - chmod +x bazelisk-linux-amd64
      - sudo mv bazelisk-linux-amd64 /usr/local/bin/bazel
      - .buildkite/build-bazel-remote.sh

  - label: ":go: Build"
    commands:
        - .buildkite/build-go.sh

    artifact_paths: 
      - dist/coverage.html
