/*
Copyright © 2024 Alexey Tereshenkov
*/
package cmd

import (
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

// RootCmd represents the base command when called without any subcommands.
// This needs to be exported to be available to `main.go`.
var RootCmd = &cobra.Command{
	Use:   "dg-query",
	Short: "A command-line utility program to query dependency graph of a codebase.",
	Long: `A command-line utility program to query dependency graph of a codebase
which operates on the adjacency list data stored as a JSON file.`,
}

// getting dependencies of targets in the dependency graph
var dependenciesCmd = &cobra.Command{
	Use:     "dependencies",
	Aliases: []string{"deps"},
	Short:   "Get dependencies of some target(s)",
	Long:    "Get dependencies of some target(s)",
	// requiring at least one target address (to get their dependencies)
	Args: cobra.MinimumNArgs(1),
	Run:  dependencies,
}

// getting dependents (reverse dependencies) of targets in the dependency graph
var dependentsCmd = &cobra.Command{
	Use:     "dependents",
	Aliases: []string{"rdeps"},
	Short:   "Get dependents of some target(s)",
	Long:    "Get dependents of some target(s)",
	// requiring at least one target address (to get their dependencies)
	Args: cobra.MinimumNArgs(1),
	Run:  dependents,
}

var metricsCmd = &cobra.Command{
	Use:   "metrics",
	Short: "Get dependency graph related metrics",
	Long:  `Get dependency graph related metrics`,
	Run:   metrics,
}

// JSON file with the dependency graph represented as an adjacency list
var dg string
var rdg string

// metrics to be generated by the `metrics` command
var metricsFlags []string

// Execute adds all child commands to the root command and sets flags appropriately.
// This is called by main.main(). It only needs to happen once to the RootCmd.
func Execute() {
	err := RootCmd.Execute()
	if err != nil {
		fmt.Println(err)
		os.Exit(1)
	}
}

func init() {
	// Here you will define your flags and configuration settings.
	// Cobra supports persistent flags, which, if defined here,
	// will be global for your application.
	RootCmd.AddCommand(metricsCmd)
	RootCmd.AddCommand(dependenciesCmd)
	RootCmd.AddCommand(dependentsCmd)

	//make dg flag global for all commands as all of them will need dg data
	RootCmd.PersistentFlags().StringVar(&dg, "dg", "", "JSON file with the dependency graph represented as an adjacency list")

	metricsCmd.Flags().StringSliceVar(&metricsFlags, "metric", []string{}, "Metrics to report")

	dependenciesCmd.Flags().BoolP("transitive", "", false, "Get transitive dependencies")
	dependenciesCmd.Flags().BoolP("reflexive", "", false, "Include input targets in the output")

	dependentsCmd.Flags().StringVar(&rdg, "rdg", "", "JSON file with the reverse dependency graph represented as an adjacency list")
	dependentsCmd.Flags().BoolP("transitive", "", false, "Get transitive dependents")
	dependentsCmd.Flags().BoolP("reflexive", "", false, "Include input targets in the output")

	// Cobra also supports local flags, which will only run
	// when this action is called directly.
	RootCmd.Flags().BoolP("toggle", "t", false, "Help message for toggle")
}
